Repository seqan/seqan3, pull requests merged in 2018-07, with the labels that each got.

#88 [FEATURE] The Argument Parser
  include/seqan3/argument_parser/all.hpp
  include/seqan3/argument_parser/argument_parser.hpp
  include/seqan3/argument_parser/auxiliary.hpp
  include/seqan3/argument_parser/detail/format_base.hpp
  include/seqan3/argument_parser/detail/format_help.hpp
  include/seqan3/argument_parser/detail/format_html.hpp
  include/seqan3/argument_parser/detail/format_man.hpp
  include/seqan3/argument_parser/detail/format_parse.hpp
  include/seqan3/argument_parser/exceptions.hpp
  include/seqan3/argument_parser/validators.hpp
  test/unit/argument_parser/CMakeLists.txt
  test/unit/argument_parser/argument_parser_design_error_test.cpp
  test/unit/argument_parser/format_parse_test.cpp
  test/unit/argument_parser/format_parse_validators_test.cpp
Labels: feature/proposal, in progress

#304 [FIX] Remove tag expression in deploy step since it breaks the pipeline.
  .jenkinsfile
Labels: bug, infrastructure

#297 [FEATURE] view::take_line
  include/seqan3/io/exception.hpp
  include/seqan3/range/detail/inherited_iterator_base.hpp
  include/seqan3/range/view/take_line.hpp
  include/seqan3/std/concept/iterator.hpp
  include/seqan3/std/view/view_all.hpp
  test/unit/range/detail/CMakeLists.txt
  test/unit/range/detail/inherited_iterator_base_test.cpp
  test/unit/range/view/CMakeLists.txt
  test/unit/range/view/view_take_line_test.cpp
Labels: feature/proposal

#302 [FEATURE] Adds header tests to jenkins pipeline
  .jenkinsfile
Labels: blocked, infrastructure

#301 [FIX] Fixes pipeline to actually call deploy node.
  .jenkinsfile
Labels: blocked, infrastructure
