Repository seqan/seqan3, pull requests merged in 2018-05, with the labels that each got.

#237 [FEATURE] null-stream output iterator.
  include/seqan3/io/detail/ignore_output_iterator.hpp
  test/unit/io/detail/CMakeLists.txt
  test/unit/io/detail/ignore_output_iterator_test.cpp
Labels: feature/proposal, in progress

#235 large update to range and view documentation
  include/seqan3/range/action/all.hpp
  include/seqan3/range/all.hpp
  include/seqan3/range/concept.hpp
  include/seqan3/range/container/concept.hpp
  include/seqan3/range/view/all.hpp
  include/seqan3/range/view/char_to.hpp
  include/seqan3/range/view/complement.hpp
  include/seqan3/range/view/convert.hpp
  include/seqan3/range/view/rank_to.hpp
  include/seqan3/range/view/single_pass_input.hpp
  include/seqan3/range/view/to_char.hpp
  include/seqan3/range/view/to_rank.hpp
  include/seqan3/range/view/trim.hpp
  test/unit/range/view/view_char_to_test.cpp
  test/unit/range/view/view_complement_test.cpp
  test/unit/range/view/view_convert_test.cpp
  test/unit/range/view/view_rank_to_test.cpp
  test/unit/range/view/view_to_char_test.cpp
  test/unit/range/view/view_to_rank_test.cpp
  test/unit/range/view/view_trim_test.cpp
Labels: in progress

#245 [FIX] error introduced by concurrent merge of previous PRs
  test/unit/io/detail/ignore_output_iterator_test.cpp
Labels: in progress

#254 Cerealisable concept
  include/seqan3/core/concept/cereal.hpp
  test/unit/core/concept/CMakeLists.txt
  test/unit/core/concept/cereal_test.cpp
Labels: enhancement, feature/proposal, test case
