Repository seqan/seqan3, pull requests merged in 2018-08, with the labels that each got.

#311 [FIX] Fixes template inspection for non template source types.
  include/seqan3/core/metafunction/template_inspection.hpp
  test/unit/core/metafunction/template_inspection_test.cpp
Labels: bug

#320 [DOC] Introduce namespace seqan3::align.
  include/seqan3/alignment/all.hpp
Labels: feature/proposal

#307 [FEATURE] structured sequence I/O
  include/seqan3/alphabet/concept_pre.hpp
  include/seqan3/alphabet/detail/member_exposure.hpp
  include/seqan3/alphabet/structure/dot_bracket3.hpp
  include/seqan3/alphabet/structure/rna_structure_concept.hpp
  include/seqan3/alphabet/structure/structured_rna.hpp
  include/seqan3/alphabet/structure/wuss.hpp
  include/seqan3/io/record.hpp
  include/seqan3/io/structure_file/all.hpp
  include/seqan3/io/structure_file/detail.hpp
  include/seqan3/io/structure_file/format_vienna.hpp
  include/seqan3/io/structure_file/input.hpp
  include/seqan3/io/structure_file/input_format_concept.hpp
  include/seqan3/io/structure_file/input_options.hpp
  include/seqan3/io/structure_file/output.hpp
  include/seqan3/io/structure_file/output_format_concept.hpp
  include/seqan3/io/structure_file/output_options.hpp
  test/unit/alphabet/structure_test.cpp
  test/unit/io/structure_file/CMakeLists.txt
  test/unit/io/structure_file/format_vienna_test.cpp
  test/unit/io/structure_file/structure_file_input_test.cpp
  test/unit/io/structure_file/structure_file_output_test.cpp
Labels: feature/proposal

#361 [FEATURE] Adds tuple_utility functions.
  include/seqan3/core/all.hpp
  include/seqan3/core/concept/tuple.hpp
  include/seqan3/core/pod_tuple.hpp
  include/seqan3/core/tuple_utility.hpp
  test/unit/core/CMakeLists.txt
  test/unit/core/my_tuple.hpp
  test/unit/core/tuple_utility_test.cpp
Labels: feature/proposal

#364 [FEATURE] Equality comparators for qualified composition against either of it's inner types.
  include/seqan3/alphabet/quality/qualified.hpp
  test/unit/alphabet/quality/qualified_test.cpp
Labels: feature/proposal

#365 reduce complexity of RNA I/O
  include/seqan3/io/structure_file/input.hpp
Labels: test case

#357 Feature/scoring scheme
  include/seqan3/alignment/scoring/all.hpp
  include/seqan3/alignment/scoring/aminoacid_scoring_scheme.hpp
  include/seqan3/alignment/scoring/nucleotide_scoring_scheme.hpp
  include/seqan3/alignment/scoring/scoring_scheme_base.hpp
  include/seqan3/std/concept/core_language.hpp
  test/unit/alignment/CMakeLists.txt
  test/unit/alignment/scoring_scheme_test.cpp
Labels: feature/proposal

#295 [FEATURE] Adds configurator interface for algorithms.
  include/seqan3/core/algorithm/all.hpp
  include/seqan3/core/algorithm/concept.hpp
  include/seqan3/core/algorithm/configuration.hpp
  include/seqan3/core/algorithm/deferred_config_element_base.hpp
  test/unit/core/algorithm/CMakeLists.txt
  test/unit/core/algorithm/configuration_test.cpp
  test/unit/core/algorithm/deferred_config_element_base_test.cpp
Labels: feature/proposal

#372 [INTERNAL] cartesian composition adjustments
  include/seqan3/alphabet/composition/cartesian_composition.hpp
  include/seqan3/alphabet/mask/masked.hpp
  include/seqan3/alphabet/quality/qualified.hpp
  include/seqan3/alphabet/structure/structured_aa.hpp
  include/seqan3/alphabet/structure/structured_rna.hpp
  test/unit/alphabet/composition/CMakeLists.txt
  test/unit/alphabet/composition/cartesian_composition_test.cpp
  test/unit/alphabet/quality/qualified_test.cpp
  test/unit/range/view/view_trim_test.cpp
Labels: design decision

#381 view::take, view::take_exactly and view::take_exactly_or_throw
  include/seqan3/io/sequence/sequence_file_format_fasta.hpp
  include/seqan3/io/sequence/sequence_file_format_fastq.hpp
  include/seqan3/io/structure_file/format_vienna.hpp
  include/seqan3/range/view/take.hpp
  include/seqan3/range/view/take_exactly.hpp
  test/unit/io/sequence/sequence_file_format_fastq_test.cpp
  test/unit/range/view/CMakeLists.txt
  test/unit/range/view/view_take_test.cpp
Labels: feature/proposal

#397 [FIX, TEST] Fixed cartesian and union composition comparison on compex types.
  include/seqan3/alphabet/composition/cartesian_composition.hpp
  include/seqan3/alphabet/composition/union_composition.hpp
  include/seqan3/alphabet/gap/gap.hpp
  test/unit/alphabet/alphabet_test.cpp
  test/unit/alphabet/composition/CMakeLists.txt
  test/unit/alphabet/composition/cartesian_composition_test.cpp
  test/unit/alphabet/composition/composition_test.cpp
Labels: in progress

#389 [FEATURE] Introduce the snippets into the alphabet module.
  include/seqan3/alphabet/adaptation/uint.hpp
  include/seqan3/alphabet/all.hpp
  include/seqan3/alphabet/aminoacid/aa20.hpp
  include/seqan3/alphabet/aminoacid/aa27.hpp
  include/seqan3/alphabet/composition/cartesian_composition.hpp
  include/seqan3/alphabet/composition/union_composition.hpp
  include/seqan3/alphabet/concept_pre.hpp
  include/seqan3/alphabet/gap/gap.hpp
  include/seqan3/alphabet/gap/gapped.hpp
  include/seqan3/alphabet/mask/mask.hpp
  include/seqan3/alphabet/mask/masked.hpp
  include/seqan3/alphabet/nucleotide/dna15.hpp
  include/seqan3/alphabet/nucleotide/dna4.hpp
  include/seqan3/alphabet/nucleotide/dna5.hpp
  include/seqan3/alphabet/nucleotide/rna15.hpp
  include/seqan3/alphabet/nucleotide/rna4.hpp
  include/seqan3/alphabet/nucleotide/rna5.hpp
  include/seqan3/alphabet/quality/phred42.hpp
  include/seqan3/alphabet/quality/phred63.hpp
  include/seqan3/alphabet/quality/phred68legacy.hpp
  include/seqan3/alphabet/quality/qualified.hpp
  include/seqan3/alphabet/structure/dot_bracket3.hpp
  include/seqan3/alphabet/structure/dssp9.hpp
  include/seqan3/alphabet/structure/structured_aa.hpp
  include/seqan3/alphabet/structure/structured_rna.hpp
  include/seqan3/alphabet/structure/wuss.hpp
  test/snippet/alphabet/adaptation/uint.cpp
  test/snippet/alphabet/all.cpp
  test/snippet/alphabet/aminoacid/aa20.cpp
  test/snippet/alphabet/aminoacid/aa27.cpp
  test/snippet/alphabet/composition/cartesian_composition.cpp
  test/snippet/alphabet/composition/union_composition.cpp
  test/snippet/alphabet/concept_pre.cpp
  test/snippet/alphabet/gap/gap.cpp
  test/snippet/alphabet/gap/gapped.cpp
  test/snippet/alphabet/mask/mask.cpp
  test/snippet/alphabet/mask/masked.cpp
  test/snippet/alphabet/nucleotide/dna15.cpp
  test/snippet/alphabet/nucleotide/dna4.cpp
  test/snippet/alphabet/nucleotide/dna5.cpp
  test/snippet/alphabet/nucleotide/rna15.cpp
  test/snippet/alphabet/nucleotide/rna4.cpp
  test/snippet/alphabet/nucleotide/rna5.cpp
  test/snippet/alphabet/quality/phred42.cpp
  test/snippet/alphabet/quality/phred63.cpp
  test/snippet/alphabet/quality/phred68legacy.cpp
  test/snippet/alphabet/quality/qualified.cpp
  test/snippet/alphabet/structure/dot_bracket3.cpp
  test/snippet/alphabet/structure/dssp9.cpp
  test/snippet/alphabet/structure/structured_aa.cpp
  test/snippet/alphabet/structure/structured_rna.cpp
  test/snippet/alphabet/structure/wuss.cpp
Labels: documentation, feature/proposal

#409 [FIX] track changes in google testing framework
  test/performance/example/example_benchmark.cpp
Labels: infrastructure
