Repository seqan/seqan3, pull requests merged in 2018-10, with the labels that each got.

#503 [NOOP] fix typo in union alphabet
  include/seqan3/alphabet/composition/union_composition.hpp
Labels: task

#516 [FIX] ambigious constructors of specialised inherited_iterator_base
  include/seqan3/range/view/persist.hpp
  include/seqan3/range/view/take.hpp
  include/seqan3/range/view/take_line.hpp
  include/seqan3/range/view/take_until.hpp
  test/unit/range/view/view_take_test.cpp
Labels: bug

#500 [FEATURE] std::from_char and std::to_char functions, tests and benchmarks.
  include/seqan3/std/charconv
  include/seqan3/std/charconv_detail.hpp
  test/performance/std/CMakeLists.txt
  test/performance/std/charconv_from_chars_benchmark.cpp
  test/performance/std/charconv_to_chars_benchmark.cpp
  test/unit/std/CMakeLists.txt
  test/unit/std/charconv_test.cpp
Labels: feature/proposal

#518 [FIX] Piping const configuration object into empty configuration object
  include/seqan3/core/algorithm/configuration.hpp
  include/seqan3/search/algorithm/search.hpp
  test/unit/core/algorithm/configuration_test.cpp
Labels: bug

#528 [fix] dont use concepts as type replacement
  include/seqan3/core/detail/strong_type.hpp
Labels: bug

#497 [FEATURE] aligned_allocator
  include/seqan3/range/container/aligned_allocator.hpp
  include/seqan3/range/container/all.hpp
  test/snippet/range/container/aligned_allocator.cpp
  test/unit/range/container/CMakeLists.txt
  test/unit/range/container/aligned_allocator_test.cpp
Labels: feature/proposal

#495 Review edit distance
  include/seqan3/alignment/matrix/alignment_matrix_formatter.hpp
  include/seqan3/alignment/matrix/alignment_score_matrix.hpp
  include/seqan3/alignment/matrix/alignment_trace_matrix.hpp
  include/seqan3/alignment/matrix/all.hpp
  include/seqan3/alignment/matrix/matrix_concept.hpp
  include/seqan3/alignment/matrix/row_wise_matrix.hpp
  include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp
  test/unit/alignment/matrix/alignment_matrix_formatter_test.cpp
Labels: task

#529 [task] gap: remove unnecessary include
  include/seqan3/alphabet/gap/gap.hpp
  test/snippet/alphabet/gap/gap.cpp
  test/unit/alphabet/gap/gap_test.cpp
Labels: task
