Repository seqan/seqan3, pull requests merged in 2018-12, with the labels that each got.

#271 Feature: code coverage test
  .travis.yml
  test/coverage/CMakeLists.txt
  test/seqan3-test.cmake
Labels: feature/proposal, infrastructure

#605 [fix] remove unnecessary includes
  include/seqan3/core/bit_manipulation.hpp
Labels: ready-to-merge

#604 [fix] documentation test should preserve newlines
  test/documentation/CMakeLists.txt
Labels: bug

#370 Feature/banded alignment
  include/seqan3/alignment/configuration/align_config_band.hpp
  include/seqan3/alignment/configuration/align_config_band_static.hpp
  include/seqan3/alignment/configuration/all.hpp
  include/seqan3/alignment/configuration/utility.hpp
  test/unit/alignment/configuration/CMakeLists.txt
  test/unit/alignment/configuration/align_config_band_test.cpp
  test/unit/alignment/configuration/utility_test.cpp
Labels: feature/proposal, ready-to-merge

#617 [fix] warnings in alphabet tests
  test/unit/alphabet/adaptation/char_test.cpp
  test/unit/alphabet/alphabet_test_template.hpp
Labels: warning

#616 [fix] warnings in core tests
  include/seqan3/core/simd/simd_algorithm.hpp
  test/unit/core/algorithm/configuration_test.cpp
  test/unit/core/bit_manipulation_test.cpp
  test/unit/core/tuple_utility_test.cpp
Labels: warning

#620 [fix] travis: doxygen ftp is not accessible anymore
  .travis.yml
Labels: bug, infrastructure

#619 [fix] warnings in range tests
  test/unit/range/container/aligned_allocator_test.cpp
  test/unit/range/view/view_char_to_test.cpp
  test/unit/range/view/view_complement_test.cpp
  test/unit/range/view/view_deep_test.cpp
  test/unit/range/view/view_take_test.cpp
Labels: warning

#597 [FIX] Fixes missing aligned_alloc on mac os
  include/seqan3/range/container/aligned_allocator.hpp
Labels: bug, ready-to-merge
