Repository seqan/seqan3, pull requests merged in 2018-04, with the labels that each got.

#226 [FIX] use non-const iterators internally to workaround bug in gcc-7.2.*
  include/seqan3/range/container/concatenated_sequences.hpp
Labels: in progress

#224 [FEATURE] Add strong type.
  include/seqan3/core/detail/strong_type.hpp
  test/unit/core/detail/CMakeLists.txt
  test/unit/core/detail/strong_type_test.cpp
Labels: feature/proposal

#230 [DOC] Fixes docu for sentinel metafunction.
  include/seqan3/core/metafunction/range.hpp
Labels: documentation, in progress

#154 [Feature] single pass input view
  include/seqan3/range/view/all.hpp
  include/seqan3/range/view/detail.hpp
  include/seqan3/range/view/single_pass_input.hpp
  test/unit/range/view/CMakeLists.txt
  test/unit/range/view/view_single_pass_input_test.cpp
Labels: feature/proposal

#234 remove one line from documentation
  include/seqan3/alphabet/nucleotide/rna15.hpp
Labels: in progress
