Repository seqan/seqan3, pull requests merged in 2018-03, with the labels that each got.

#158 Document gap alphabet and add tests
  include/seqan3/alphabet/gap/gapped.hpp
  test/alphabet/alphabet_test.cpp
Labels: documentation, test case

#188 [DOC] Added template page for serialisation.
  include/seqan3/io/all.hpp
Labels: documentation

#112 [FEATURE] added benchmark folder and an example benchmark
  .travis.yml
  benchmark/CMakeLists.txt
  benchmark/alphabet/CMakeLists.txt
  benchmark/alphabet/alphabet_benchmark.cpp
  benchmark/example/CMakeLists.txt
  benchmark/example/example_benchmark.cpp
Labels: feature/proposal

#196 [DOC] Small fix doc
  include/seqan3/core/detail/terminal.hpp
Labels: documentation

#197 [INTERNAL] Add decorator directory.
  include/seqan3/range/all.hpp
  include/seqan3/range/decorator/all.cpp
Labels: feature/proposal

#201 fix wuss alphabet
  include/seqan3/alphabet/structure/wuss.hpp
Labels: bug

#202 refactor cmakefiles in test/
  build_system/seqan3-config.cmake
  test/io/CMakeLists.txt
  test/performance/CMakeLists.txt
  test/seqan3-test.cmake
  test/unit/CMakeLists.txt
Labels: infrastructure

#208 Update README.md
  README.md
Labels: documentation

#162 [Feature] stream concept and output iterator.
  include/seqan3/io/concept.hpp
  include/seqan3/io/detail/output_iterator_conversion_adaptor.hpp
  test/io/CMakeLists.txt
  test/io/util/CMakeLists.txt
  test/unit/io/CMakeLists.txt
  test/unit/io/concept_test.cpp
  test/unit/io/detail/CMakeLists.txt
  test/unit/io/detail/output_iterator_conversion_adaptor_test.cpp
Labels: feature/proposal

#216 remove test/io/util/CMakeLists.txt
  test/io/util/CMakeLists.txt
Labels: task
