Repository seqan/seqan3, pull requests merged in 2018-11, with the labels that each got.

#505 simd: add first batch of simd functionality
  include/seqan3/core/simd/all.hpp
  include/seqan3/core/simd/concept.hpp
  include/seqan3/core/simd/detail/builtin_simd.hpp
  include/seqan3/core/simd/detail/default_simd_backend.hpp
  include/seqan3/core/simd/detail/default_simd_length.hpp
  include/seqan3/core/simd/simd.hpp
  include/seqan3/core/simd/simd_algorithm.hpp
  include/seqan3/core/simd/simd_debug_stream.hpp
  include/seqan3/core/simd/simd_traits.hpp
  test/include/seqan3/test/simd_utility.hpp
  test/snippet/core/simd/detail/builtin_simd.cpp
  test/snippet/core/simd/detail/default_simd_max_length.cpp
  test/snippet/core/simd/detail/is_builtin_simd.cpp
  test/snippet/core/simd/fill.cpp
  test/snippet/core/simd/iota.cpp
  test/snippet/core/simd/simd.cpp
  test/snippet/core/simd/simd_test_utility.cpp
  test/snippet/core/simd/simd_traits.cpp
  test/unit/core/simd/CMakeLists.txt
  test/unit/core/simd/detail/CMakeLists.txt
  test/unit/core/simd/detail/builtin_simd_test.cpp
  test/unit/core/simd/detail/default_simd_backend_test.cpp
  test/unit/core/simd/detail/default_simd_length_builtin_simd_test.cpp
  test/unit/core/simd/simd_algorithm_test.cpp
  test/unit/core/simd/simd_debug_stream_test.cpp
  test/unit/core/simd/simd_test.cpp
Labels: feature/proposal

#554 [fix] clang: defaulted definition of copy assignment operator is not constexpr
  test/unit/range/detail/inherited_iterator_base_test.cpp
Labels: bug

#555 [fix] clang: unused variables
  test/unit/range/container/aligned_allocator_test.cpp
  test/unit/range/detail/random_access_iterator_test.cpp
Labels: warning

#556 [fix] clang: variable is uninitialized when used here
  test/unit/range/detail/random_access_iterator_test.cpp
Labels: warning

#566 [NOP] Adds googlemock.
  test/seqan3-test.cmake
Labels: infrastructure

#565 Fixes header includes.
  include/seqan3/argument_parser/exceptions.hpp
  include/seqan3/io/alignment_file/header.hpp
  include/seqan3/io/structure_file/output_format_concept.hpp
  test/header/CMakeLists.txt
Labels: bug

#558 [fix] clang: use source-level subsumption
  include/seqan3/core/metafunction/range.hpp
Labels: bug

#539 [FEATURE] Add std::hash for semi_alphabets and view::kmer_hash
  include/seqan3/alphabet/concept.hpp
  include/seqan3/alphabet/detail/hash.hpp
  include/seqan3/range/view/kmer_hash.hpp
  test/snippet/range/view/kmer_hash.cpp
  test/unit/alphabet/alphabet_test.cpp
  test/unit/range/view/CMakeLists.txt
  test/unit/range/view/view_kmer_hash_test.cpp
Labels: feature/proposal

#582 [FIX] Fixes scoring scheme matrix size type.
  include/seqan3/alignment/scoring/scoring_scheme_base.hpp
Labels: bug
