Repository seqan/seqan3, pull requests merged in 2018-09, with the labels that each got.

#369 Feature/affine gaps
  include/seqan3/alignment/configuration/align_config_gap.hpp
  include/seqan3/alignment/configuration/all.hpp
  include/seqan3/alignment/configuration/utility.hpp
  include/seqan3/alignment/scoring/gap_scheme.hpp
  include/seqan3/core/algorithm/configuration.hpp
  test/unit/alignment/CMakeLists.txt
  test/unit/alignment/configuration/CMakeLists.txt
  test/unit/alignment/configuration/align_config_gap_test.cpp
  test/unit/alignment/configuration/utility_test.cpp
  test/unit/alignment/gap_scheme_test.cpp
Labels: feature/proposal

#400 [FEATURE] Introduces view::get functionality, along with related exam…
  include/seqan3/core/concept/tuple.hpp
  include/seqan3/range/view/get.hpp
  test/snippet/range/view/get.cpp
  test/unit/range/view/CMakeLists.txt
  test/unit/range/view/view_get_test.cpp
Labels: feature/proposal

#417 Keep folder structure of snippet binaries
  test/snippet/CMakeLists.txt
Labels: enhancement

#415 [FEATURE] The SAM tag dictionary.
  include/seqan3/io/alignment/align_file.hpp
  include/seqan3/io/alignment/align_file_detail.hpp
  include/seqan3/io/alignment/align_file_in.hpp
  include/seqan3/io/alignment/align_file_out.hpp
  include/seqan3/io/alignment_file/all.hpp
  include/seqan3/io/alignment_file/detail.hpp
  include/seqan3/io/alignment_file/sam_tag_dictionary.hpp
  test/snippet/io/alignment_file/sam_tag_dictionary/general_usage.cpp
  test/snippet/io/alignment_file/sam_tag_dictionary/sam_tag_dictionary.cpp
  test/snippet/io/alignment_file/sam_tag_dictionary/unknown_tag.cpp
  test/unit/alignment/aligned_sequence_test.cpp
  test/unit/io/alignment_file/CMakeLists.txt
  test/unit/io/alignment_file/sam_tag_dictionary_test.cpp
Labels: feature/proposal, in progress

#434 [FIX] aligned_sequence_test.cpp:58:45: error: ‘*((void*)& cval +1)’ m…
  test/unit/alignment/aligned_sequence_test.cpp
Labels: bug

#430 [FIX,DOC] Fixes group of aligned sequence submodule
  include/seqan3/alignment/aligned_sequence/all.hpp
Labels: documentation

#390 [FEATURE] introduce the snippets into the alignment module as well.
  include/seqan3/alignment/scoring/aminoacid_scoring_scheme.hpp
  include/seqan3/alignment/scoring/nucleotide_scoring_scheme.hpp
  test/snippet/alignment/scoring/aminoacid_scoring_scheme.cpp
  test/snippet/alignment/scoring/nucleotide_scoring_scheme.cpp
Labels: documentation, feature/proposal

#402 [FIX, TEST] fix a wrong constexpr condition and add a test
  include/seqan3/alphabet/concept_pre.hpp
  include/seqan3/alphabet/detail/member_exposure.hpp
  include/seqan3/alphabet/structure/dot_bracket3.hpp
  include/seqan3/alphabet/structure/rna_structure_concept.hpp
  include/seqan3/alphabet/structure/structured_rna.hpp
  include/seqan3/alphabet/structure/wuss.hpp
  include/seqan3/io/structure_file/detail.hpp
  test/snippet/alphabet/concept_pre.cpp
  test/unit/alphabet/structure_test.cpp
Labels: bug

#391 [FEATURE] introduce the snippets into the argument_parser module.
  include/seqan3/argument_parser/argument_parser.hpp
  include/seqan3/argument_parser/auxiliary.hpp
  include/seqan3/argument_parser/validators.hpp
  test/snippet/argument_parser/argument_parser_1.cpp
  test/snippet/argument_parser/argument_parser_2.cpp
  test/snippet/argument_parser/argument_parser_3.cpp
  test/snippet/argument_parser/auxiliary.cpp
  test/snippet/argument_parser/validators_1.cpp
  test/snippet/argument_parser/validators_2.cpp
  test/snippet/argument_parser/validators_3.cpp
  test/snippet/argument_parser/validators_4.cpp
Labels: documentation, feature/proposal

#394 [FEATURE] Introduce the snippets into the core module.
  include/seqan3/core/add_enum_bitwise_operators.hpp
  include/seqan3/core/algorithm/configuration.hpp
  include/seqan3/core/algorithm/deferred_config_element_base.hpp
  include/seqan3/core/detail/reflection.hpp
  include/seqan3/core/detail/strong_type.hpp
  include/seqan3/core/metafunction/range.hpp
  include/seqan3/core/metafunction/template_inspection.hpp
  include/seqan3/core/pod_tuple.hpp
  include/seqan3/core/tuple_utility.hpp
  test/snippet/core/add_enum_bitwise_operators.cpp
  test/snippet/core/algorithm/configuration.cpp
  test/snippet/core/algorithm/deferred_config_element_base.cpp
  test/snippet/core/detail/reflection.cpp
  test/snippet/core/detail/strong_type.cpp
  test/snippet/core/detail/strong_type_2.cpp
  test/snippet/core/metafunction/range.cpp
  test/snippet/core/metafunction/template_inspection.cpp
  test/snippet/core/pod_tuple.cpp
  test/snippet/core/tuple_utility.cpp
Labels: documentation, feature/proposal

#437 Change documentation group: structure -> structure_file
  include/seqan3/io/structure_file/all.hpp
  include/seqan3/io/structure_file/detail.hpp
  include/seqan3/io/structure_file/format_vienna.hpp
  include/seqan3/io/structure_file/input.hpp
  include/seqan3/io/structure_file/input_format_concept.hpp
  include/seqan3/io/structure_file/input_options.hpp
  include/seqan3/io/structure_file/output.hpp
  include/seqan3/io/structure_file/output_format_concept.hpp
  include/seqan3/io/structure_file/output_options.hpp
Labels: documentation

#426 free ends alignment configuration
  include/seqan3/alignment/configuration/align_config_sequence_ends.hpp
  include/seqan3/alignment/configuration/all.hpp
  include/seqan3/alignment/configuration/utility.hpp
  test/unit/alignment/configuration/CMakeLists.txt
  test/unit/alignment/configuration/align_config_sequence_ends_test.cpp
  test/unit/alignment/configuration/utility_test.cpp
Labels: feature/proposal

#428 Configuration element for alignment scoring
  include/seqan3/alignment/configuration/align_config_score.hpp
  include/seqan3/alignment/configuration/all.hpp
  test/unit/alignment/configuration/CMakeLists.txt
  test/unit/alignment/configuration/align_config_score_test.cpp
Labels: feature/proposal

#431 [FEATURE] edit distance alignment
  include/seqan3/alignment/matrix/alignment_matrix_formatter.hpp
  include/seqan3/alignment/matrix/alignment_score_matrix.hpp
  include/seqan3/alignment/matrix/alignment_trace_matrix.hpp
  include/seqan3/alignment/matrix/all.hpp
  include/seqan3/alignment/matrix/matrix_concept.hpp
  include/seqan3/alignment/matrix/rowwise_matrix.hpp
  include/seqan3/alignment/pairwise_alignment_edit_distance_unbanded.hpp
  test/snippet/alignment/matrix/alignment_matrix_formatter.cpp
  test/snippet/alignment/matrix/alignment_matrix_formatter.out
  test/snippet/alignment/matrix/alignment_score_matrix.cpp
  test/snippet/alignment/matrix/alignment_score_matrix.out
  test/snippet/alignment/matrix/alignment_trace_matrix.cpp
  test/snippet/alignment/matrix/alignment_trace_matrix.out
  test/snippet/alignment/matrix/alignment_trace_matrix_vector.cpp
  test/snippet/alignment/matrix/alignment_trace_matrix_vector.out
  test/unit/alignment/CMakeLists.txt
  test/unit/alignment/fixture/alignment_fixture.hpp
  test/unit/alignment/fixture/config_global.hpp
  test/unit/alignment/fixture/config_max_errors.hpp
  test/unit/alignment/fixture/config_semi_global.hpp
  test/unit/alignment/fixture/config_unbanded.hpp
  test/unit/alignment/fixture/global_edit_distance_max_errors_unbanded.hpp
  test/unit/alignment/fixture/global_edit_distance_unbanded.hpp
  test/unit/alignment/fixture/semi_global_edit_distance_max_errors_unbanded.hpp
  test/unit/alignment/fixture/semi_global_edit_distance_unbanded.hpp
  test/unit/alignment/matrix/CMakeLists.txt
  test/unit/alignment/matrix/alignment_matrix_formatter_test.cpp
  test/unit/alignment/matrix/alignment_matrix_test.cpp
  test/unit/alignment/pairwise_alignment_edit_distance_unbanded_test.cpp
Labels: feature/proposal

#440 [FIX] Fixes template inspection for enum values.
  include/seqan3/core/metafunction/template_inspection.hpp
  test/unit/core/metafunction/template_inspection_test.cpp
Labels: bug

#452 [DOC] fix the structure file module name
  include/seqan3/io/structure_file/all.hpp
Labels: documentation

#439 semi_global now tracks optimal position
  include/seqan3/alignment/matrix/alignment_trace_matrix.hpp
  include/seqan3/alignment/matrix/all.hpp
  include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp
  test/unit/alignment/pairwise/edit_distance_unbanded_test.cpp
  test/unit/alignment/pairwise/fixture/alignment_fixture.hpp
  test/unit/alignment/pairwise/fixture/global_edit_distance_max_errors_unbanded.hpp
  test/unit/alignment/pairwise/fixture/global_edit_distance_unbanded.hpp
  test/unit/alignment/pairwise/fixture/semi_global_edit_distance_max_errors_unbanded.hpp
  test/unit/alignment/pairwise/fixture/semi_global_edit_distance_unbanded.hpp
Labels: task

#453 Feature/align pairwise
  include/seqan3/alignment/configuration/align_config_edit.hpp
  include/seqan3/alignment/pairwise/align_pairwise.hpp
  include/seqan3/alignment/pairwise/alignment_selector.hpp
  include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp
  include/seqan3/alignment/pairwise/execution/alignment_executor_two_way.hpp
  include/seqan3/alignment/pairwise/execution/alignment_range.hpp
  include/seqan3/alignment/pairwise/execution/execution_handler_sequential.hpp
  test/unit/alignment/configuration/align_config_edit_test.cpp
  test/unit/alignment/pairwise/CMakeLists.txt
  test/unit/alignment/pairwise/align_pairwise_test.cpp
  test/unit/alignment/pairwise/alignment_selector_test.cpp
  test/unit/alignment/pairwise/execution/alignment_executor_two_way_test.cpp
Labels: feature/proposal

#460 [FIX] Fixes const precedence issue in debug stream.
  include/seqan3/io/stream/debug_stream.hpp
Labels: bug

#459 [FIX] Fixes pipe with empty configuration onf left hand side.
  include/seqan3/core/algorithm/configuration.hpp
  test/unit/core/algorithm/configuration_test.cpp
Labels: bug

#474 [DOC] Add missing throws documentation to argument_parser::parse().
  include/seqan3/argument_parser/argument_parser.hpp
Labels: documentation
